/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package cat.diba.oficinasvivienda.model.impl;

import cat.diba.oficinasvivienda.model.OficinaServicioMunicipio;
import cat.diba.oficinasvivienda.model.OficinaServicioMunicipioModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the OficinaServicioMunicipio service. Represents a row in the &quot;OfiVi_OficinaServicioMunicipio&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link cat.diba.oficinasvivienda.model.OficinaServicioMunicipioModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OficinaServicioMunicipioImpl}.
 * </p>
 *
 * @author gonzalezscr
 * @see OficinaServicioMunicipioImpl
 * @see cat.diba.oficinasvivienda.model.OficinaServicioMunicipio
 * @see cat.diba.oficinasvivienda.model.OficinaServicioMunicipioModel
 * @generated
 */
public class OficinaServicioMunicipioModelImpl extends BaseModelImpl<OficinaServicioMunicipio>
	implements OficinaServicioMunicipioModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a oficina servicio municipio model instance should use the {@link cat.diba.oficinasvivienda.model.OficinaServicioMunicipio} interface instead.
	 */
	public static final String TABLE_NAME = "OfiVi_OficinaServicioMunicipio";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "idOficina", Types.BIGINT },
			{ "idServicio", Types.BIGINT },
			{ "codigoIne", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table OfiVi_OficinaServicioMunicipio (id_ LONG not null primary key,companyId LONG,groupId LONG,idOficina LONG,idServicio LONG,codigoIne VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table OfiVi_OficinaServicioMunicipio";
	public static final String ORDER_BY_JPQL = " ORDER BY oficinaServicioMunicipio.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY OfiVi_OficinaServicioMunicipio.id_ ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.cat.diba.oficinasvivienda.model.OficinaServicioMunicipio"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.cat.diba.oficinasvivienda.model.OficinaServicioMunicipio"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.cat.diba.oficinasvivienda.model.OficinaServicioMunicipio"),
			true);
	public static long CODIGOINE_COLUMN_BITMASK = 1L;
	public static long COMPANYID_COLUMN_BITMASK = 2L;
	public static long GROUPID_COLUMN_BITMASK = 4L;
	public static long IDOFICINA_COLUMN_BITMASK = 8L;
	public static long IDSERVICIO_COLUMN_BITMASK = 16L;
	public static long ID_COLUMN_BITMASK = 32L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.cat.diba.oficinasvivienda.model.OficinaServicioMunicipio"));

	public OficinaServicioMunicipioModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return OficinaServicioMunicipio.class;
	}

	@Override
	public String getModelClassName() {
		return OficinaServicioMunicipio.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("companyId", getCompanyId());
		attributes.put("groupId", getGroupId());
		attributes.put("idOficina", getIdOficina());
		attributes.put("idServicio", getIdServicio());
		attributes.put("codigoIne", getCodigoIne());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long idOficina = (Long)attributes.get("idOficina");

		if (idOficina != null) {
			setIdOficina(idOficina);
		}

		Long idServicio = (Long)attributes.get("idServicio");

		if (idServicio != null) {
			setIdServicio(idServicio);
		}

		String codigoIne = (String)attributes.get("codigoIne");

		if (codigoIne != null) {
			setCodigoIne(codigoIne);
		}
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getIdOficina() {
		return _idOficina;
	}

	@Override
	public void setIdOficina(long idOficina) {
		_columnBitmask |= IDOFICINA_COLUMN_BITMASK;

		if (!_setOriginalIdOficina) {
			_setOriginalIdOficina = true;

			_originalIdOficina = _idOficina;
		}

		_idOficina = idOficina;
	}

	public long getOriginalIdOficina() {
		return _originalIdOficina;
	}

	@Override
	public long getIdServicio() {
		return _idServicio;
	}

	@Override
	public void setIdServicio(long idServicio) {
		_columnBitmask |= IDSERVICIO_COLUMN_BITMASK;

		if (!_setOriginalIdServicio) {
			_setOriginalIdServicio = true;

			_originalIdServicio = _idServicio;
		}

		_idServicio = idServicio;
	}

	public long getOriginalIdServicio() {
		return _originalIdServicio;
	}

	@Override
	public String getCodigoIne() {
		if (_codigoIne == null) {
			return StringPool.BLANK;
		}
		else {
			return _codigoIne;
		}
	}

	@Override
	public void setCodigoIne(String codigoIne) {
		_columnBitmask |= CODIGOINE_COLUMN_BITMASK;

		if (_originalCodigoIne == null) {
			_originalCodigoIne = _codigoIne;
		}

		_codigoIne = codigoIne;
	}

	public String getOriginalCodigoIne() {
		return GetterUtil.getString(_originalCodigoIne);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			OficinaServicioMunicipio.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public OficinaServicioMunicipio toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (OficinaServicioMunicipio)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		OficinaServicioMunicipioImpl oficinaServicioMunicipioImpl = new OficinaServicioMunicipioImpl();

		oficinaServicioMunicipioImpl.setId(getId());
		oficinaServicioMunicipioImpl.setCompanyId(getCompanyId());
		oficinaServicioMunicipioImpl.setGroupId(getGroupId());
		oficinaServicioMunicipioImpl.setIdOficina(getIdOficina());
		oficinaServicioMunicipioImpl.setIdServicio(getIdServicio());
		oficinaServicioMunicipioImpl.setCodigoIne(getCodigoIne());

		oficinaServicioMunicipioImpl.resetOriginalValues();

		return oficinaServicioMunicipioImpl;
	}

	@Override
	public int compareTo(OficinaServicioMunicipio oficinaServicioMunicipio) {
		long primaryKey = oficinaServicioMunicipio.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof OficinaServicioMunicipio)) {
			return false;
		}

		OficinaServicioMunicipio oficinaServicioMunicipio = (OficinaServicioMunicipio)obj;

		long primaryKey = oficinaServicioMunicipio.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		OficinaServicioMunicipioModelImpl oficinaServicioMunicipioModelImpl = this;

		oficinaServicioMunicipioModelImpl._originalCompanyId = oficinaServicioMunicipioModelImpl._companyId;

		oficinaServicioMunicipioModelImpl._setOriginalCompanyId = false;

		oficinaServicioMunicipioModelImpl._originalGroupId = oficinaServicioMunicipioModelImpl._groupId;

		oficinaServicioMunicipioModelImpl._setOriginalGroupId = false;

		oficinaServicioMunicipioModelImpl._originalIdOficina = oficinaServicioMunicipioModelImpl._idOficina;

		oficinaServicioMunicipioModelImpl._setOriginalIdOficina = false;

		oficinaServicioMunicipioModelImpl._originalIdServicio = oficinaServicioMunicipioModelImpl._idServicio;

		oficinaServicioMunicipioModelImpl._setOriginalIdServicio = false;

		oficinaServicioMunicipioModelImpl._originalCodigoIne = oficinaServicioMunicipioModelImpl._codigoIne;

		oficinaServicioMunicipioModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<OficinaServicioMunicipio> toCacheModel() {
		OficinaServicioMunicipioCacheModel oficinaServicioMunicipioCacheModel = new OficinaServicioMunicipioCacheModel();

		oficinaServicioMunicipioCacheModel.id = getId();

		oficinaServicioMunicipioCacheModel.companyId = getCompanyId();

		oficinaServicioMunicipioCacheModel.groupId = getGroupId();

		oficinaServicioMunicipioCacheModel.idOficina = getIdOficina();

		oficinaServicioMunicipioCacheModel.idServicio = getIdServicio();

		oficinaServicioMunicipioCacheModel.codigoIne = getCodigoIne();

		String codigoIne = oficinaServicioMunicipioCacheModel.codigoIne;

		if ((codigoIne != null) && (codigoIne.length() == 0)) {
			oficinaServicioMunicipioCacheModel.codigoIne = null;
		}

		return oficinaServicioMunicipioCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", idOficina=");
		sb.append(getIdOficina());
		sb.append(", idServicio=");
		sb.append(getIdServicio());
		sb.append(", codigoIne=");
		sb.append(getCodigoIne());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("cat.diba.oficinasvivienda.model.OficinaServicioMunicipio");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idOficina</column-name><column-value><![CDATA[");
		sb.append(getIdOficina());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idServicio</column-name><column-value><![CDATA[");
		sb.append(getIdServicio());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>codigoIne</column-name><column-value><![CDATA[");
		sb.append(getCodigoIne());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = OficinaServicioMunicipio.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			OficinaServicioMunicipio.class
		};
	private long _id;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _idOficina;
	private long _originalIdOficina;
	private boolean _setOriginalIdOficina;
	private long _idServicio;
	private long _originalIdServicio;
	private boolean _setOriginalIdServicio;
	private String _codigoIne;
	private String _originalCodigoIne;
	private long _columnBitmask;
	private OficinaServicioMunicipio _escapedModel;
}