/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package cat.diba.oficinasvivienda.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Municipio service. Represents a row in the &quot;OfiVi_Municipio&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link cat.diba.oficinasvivienda.model.impl.MunicipioModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link cat.diba.oficinasvivienda.model.impl.MunicipioImpl}.
 * </p>
 *
 * @author gonzalezscr
 * @see Municipio
 * @see cat.diba.oficinasvivienda.model.impl.MunicipioImpl
 * @see cat.diba.oficinasvivienda.model.impl.MunicipioModelImpl
 * @generated
 */
public interface MunicipioModel extends BaseModel<Municipio> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a municipio model instance should use the {@link Municipio} interface instead.
	 */

	/**
	 * Returns the primary key of this municipio.
	 *
	 * @return the primary key of this municipio
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this municipio.
	 *
	 * @param primaryKey the primary key of this municipio
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the codigo ine of this municipio.
	 *
	 * @return the codigo ine of this municipio
	 */
	@AutoEscape
	public String getCodigoIne();

	/**
	 * Sets the codigo ine of this municipio.
	 *
	 * @param codigoIne the codigo ine of this municipio
	 */
	public void setCodigoIne(String codigoIne);

	/**
	 * Returns the nombre of this municipio.
	 *
	 * @return the nombre of this municipio
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this municipio.
	 *
	 * @param nombre the nombre of this municipio
	 */
	public void setNombre(String nombre);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(cat.diba.oficinasvivienda.model.Municipio municipio);

	@Override
	public int hashCode();

	@Override
	public CacheModel<cat.diba.oficinasvivienda.model.Municipio> toCacheModel();

	@Override
	public cat.diba.oficinasvivienda.model.Municipio toEscapedModel();

	@Override
	public cat.diba.oficinasvivienda.model.Municipio toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}